# Generated by Django 5.2.17 on 2026-08-06 02:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trends", "0002_trend_analyzed_at_trend_confidence_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("business_relevance", models.TextField()),
                ("founder_relevance", models.TextField()),
                ("entrepreneurship_relevance", models.TextField()),
                ("ai_relevance", models.TextField()),
                ("trend_score", models.PositiveSmallIntegerField()),
                ("opportunity_score", models.PositiveSmallIntegerField()),
                ("confidence_score", models.PositiveSmallIntegerField()),
                ("model_used", models.CharField(max_length=100)),
                ("prompt_version", models.CharField(default="v1", max_length=20)),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="trends.trend",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "trend analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["trend", "created_at"], name="trend_analy_trend_i_276521_idx"
                    )
                ],
            },
        ),
    ]
