# Generated by Django 5.2.17 on 2026-08-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendanalysis',
            name='best_audience',
            field=models.CharField(choices=[('content_creators', 'Content Creators'), ('founders', 'Founders'), ('investors', 'Investors')], default='founders', max_length=20),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='content_creator_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='founder_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='investor_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='suggested_content_angle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='trend_stage',
            field=models.CharField(choices=[('emerging', 'Emerging'), ('growing', 'Growing'), ('peaking', 'Peaking'), ('declining', 'Declining')], default='emerging', max_length=20),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='what_is_happening',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trendanalysis',
            name='why_it_matters',
            field=models.TextField(default=''),
        ),
    ]
