# Generated by Django 5.2.17 on 2026-09-17 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_legacy_analysis_owners(apps, schema_editor):
    """Recover ownership from completed user-triggered re-analysis jobs.

    Older automatic analyses have no trustworthy owner, so they remain private
    to no account rather than being exposed to the next visitor.
    """
    Analysis = apps.get_model("trend_analysis", "TrendAnalysis")
    AIJob = apps.get_model("core", "AIJob")
    for job in AIJob.objects.exclude(created_by_id=None).filter(job_type="reanalyze_trend"):
        analysis_id = (job.result or {}).get("analysis_id")
        if analysis_id:
            Analysis.objects.filter(id=analysis_id, created_by_id=None).update(
                created_by_id=job.created_by_id
            )


class Migration(migrations.Migration):

    dependencies = [
        ("trend_analysis", "0005_trendanalysis_opportunity_editorial_copy"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trendanalysis",
            name="action_summary",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trend_analyses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="estimated_lifespan",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="summary",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="why_spreading",
            field=models.TextField(default=""),
        ),
        migrations.RunPython(assign_legacy_analysis_owners, migrations.RunPython.noop),
    ]
