# Generated by Django 5.2.17 on 2026-08-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trend",
            name="analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trend",
            name="confidence_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trend",
            name="opportunity_score",
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="trend",
            name="trend_score",
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="trend",
            index=models.Index(fields=["trend_score"], name="trends_tren_trend_s_7a7a32_idx"),
        ),
        migrations.AddIndex(
            model_name="trend",
            index=models.Index(fields=["opportunity_score"], name="trends_tren_opportu_4b43ca_idx"),
        ),
    ]
