# Generated by Django 5.2.17 on 2026-08-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_trend_analyzed_at_trend_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='best_audience',
            field=models.CharField(blank=True, choices=[('content_creators', 'Content Creators'), ('founders', 'Founders'), ('investors', 'Investors')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trend',
            name='content_creator_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='founder_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='investor_score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='trend',
            name='suggested_content_angle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trend',
            name='trend_stage',
            field=models.CharField(blank=True, choices=[('emerging', 'Emerging'), ('growing', 'Growing'), ('peaking', 'Peaking'), ('declining', 'Declining')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='trend',
            name='what_is_happening',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trend',
            name='why_it_matters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='trend',
            index=models.Index(fields=['best_audience'], name='trends_tren_best_au_c9745a_idx'),
        ),
    ]
