# Generated by Django 5.2.17 on 2026-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_sources', '0002_platform_credibility_weight'),
        ('trends', '0003_trend_best_audience_trend_content_creator_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='action_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trendsourcelink',
            name='relevance_score',
            field=models.PositiveSmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='trend',
            name='dedup_key',
            field=models.CharField(db_index=True, help_text='Normalized title used to match new signals to an existing trend.', max_length=300, unique=True),
        ),
        migrations.AddIndex(
            model_name='trendsourcelink',
            index=models.Index(fields=['trend', '-created_at'], name='trends_tren_trend_i_fbe7e5_idx'),
        ),
    ]
