# Generated by Django 5.2.17 on 2026-08-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0004_trend_action_summary_trendsourcelink_relevance_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='active_dedup_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trend',
            name='dedup_key',
            field=models.CharField(db_index=True, help_text='Normalized title used to match new signals to an existing trend.', max_length=300),
        ),
    ]
