# Generated by Django 5.2.17 on 2026-08-06 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trends", "0002_trend_analyzed_at_trend_confidence_score_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentBrief",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("business_angle", models.TextField(blank=True)),
                ("founder_angle", models.TextField(blank=True)),
                ("educational_angle", models.TextField(blank=True)),
                ("marketing_angle", models.TextField(blank=True)),
                ("talking_points", models.JSONField(blank=True, default=list)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_briefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_briefs",
                        to="trends.trend",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("hook", "Hook"),
                            ("script_30", "30s script"),
                            ("script_60", "60s script"),
                            ("cta", "Call to action"),
                            ("hashtags", "Hashtags"),
                            ("thumbnail_suggestion", "Thumbnail suggestion"),
                            ("remix_template", "Remix template"),
                        ],
                        max_length=30,
                    ),
                ),
                ("body", models.TextField()),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("is_saved", models.BooleanField(default=False)),
                ("model_used", models.CharField(blank=True, max_length=100)),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_content",
                        to="content_studio.contentbrief",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_content",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contentbrief",
            index=models.Index(
                fields=["trend", "created_at"], name="content_stu_trend_i_a8391b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcontent",
            index=models.Index(
                fields=["created_by", "is_saved"], name="content_stu_created_043e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedcontent",
            index=models.Index(
                fields=["brief", "content_type"], name="content_stu_brief_i_d34d2a_idx"
            ),
        ),
    ]
