# Generated by Django 5.2.17 on 2026-08-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbrief',
            name='content_angle',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='perspective',
            field=models.CharField(blank=True, choices=[('content_creators', 'Content Creators'), ('founders', 'Founders'), ('investors', 'Investors')], default='', max_length=20),
        ),
    ]
