# Generated by Django 5.2.17 on 2026-08-31 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0002_contentbrief_content_angle_contentbrief_perspective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='generatedcontent',
            constraint=models.UniqueConstraint(fields=('brief', 'content_type', 'version'), name='unique_content_version_per_brief_type'),
        ),
    ]
