# Generated by Django 5.2.17 on 2026-08-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_studio', '0003_generatedcontent_unique_content_version_per_brief_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcontent',
            name='content_type',
            field=models.CharField(choices=[('hook', 'Hook'), ('script_30', '30s script'), ('post', 'Post'), ('script_60', '60s script'), ('cta', 'Call to action'), ('hashtags', 'Hashtags'), ('thumbnail_suggestion', 'Thumbnail suggestion'), ('remix_template', 'Remix template')], max_length=30),
        ),
    ]
