# Generated by Django 5.2.17 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_studio", "0004_alter_generatedcontent_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedcontent",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("hook", "Hook"),
                    ("script_30", "30s script"),
                    ("post", "Post"),
                ],
                max_length=30,
            ),
        ),
    ]
