# Generated by Django 5.2.17 on 2026-08-06 01:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "adapter_key",
                    models.CharField(
                        help_text="Must match a slug registered via @register_adapter.",
                        max_length=50,
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("poll_interval_minutes", models.PositiveIntegerField(default=60)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RawTrendSignal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("summary", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_signals",
                        to="trend_sources.platform",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["platform", "created_at"], name="trend_sourc_platfor_cf33d8_idx"
                    ),
                    models.Index(fields=["processed_at"], name="trend_sourc_process_946248_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "external_id"), name="unique_signal_per_platform"
                    )
                ],
            },
        ),
    ]
