# Generated by Django 5.2.17 on 2026-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='credibility_weight',
            field=models.PositiveSmallIntegerField(default=50, help_text='Editorial credibility score from 0-100, used as one input to AI analysis.'),
        ),
    ]
