# Generated by Django 5.2.17 on 2026-08-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text="Google's stable subject identifier, for accounts linked via Google OAuth.", max_length=255, null=True, unique=True),
        ),
    ]
