# Generated by Django 5.2.17 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_google_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_code_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
